// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idcpitlkmjnachnkhphb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkY3BpdGxrbWpuYWNobmtocGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDU1NDcsImV4cCI6MjA2NzkyMTU0N30.Vg9NWoet-Xe-LRxxwsKtDgjFj2FdKQ9RBgaCFHS65GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});